#!/usr/bin/env bash
# lib/init.sh - Initialize a new kb vault
# Requires: VAULT_ROOT (if called via dispatcher), KB_ROOT, KB_VERSION

# Validate a path is safe (no path traversal)
_validate_path() {
    local path="$1"
    if [[ "$path" == *".."* ]]; then
        printf 'Error: path traversal ("..") is not allowed\n' >&2
        return 1
    fi
    return 0
}

kb_init() {
    local target_dir=""
    local force=0
    local install_hooks=0

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --force)
                force=1
                shift
                ;;
            --hooks)
                install_hooks=1
                shift
                ;;
            -*)
                printf 'Error: unknown flag: %s\n' "$1" >&2
                return 1
                ;;
            *)
                if [[ -z "$target_dir" ]]; then
                    target_dir="$1"
                else
                    printf 'Error: unexpected argument: %s\n' "$1" >&2
                    return 1
                fi
                shift
                ;;
        esac
    done

    # Default to current directory
    if [[ -z "$target_dir" ]]; then
        target_dir="."
    fi

    # Validate path safety
    _validate_path "$target_dir" || return 1

    # Resolve to absolute path
    if [[ "$target_dir" == "." ]]; then
        target_dir="$(pwd)"
    elif [[ "$target_dir" != /* ]]; then
        target_dir="$(pwd)/$target_dir"
    fi

    # Check if vault already exists
    if [[ -d "$target_dir/.kb" ]] && [[ "$force" -eq 0 ]]; then
        printf 'Error: vault already exists at %s\n' "$target_dir" >&2
        printf 'Use --force to reinitialize (existing files will be overwritten)\n' >&2
        return 1
    fi

    # Ensure KB_ROOT is set so we can find templates
    if [[ -z "${KB_ROOT:-}" ]]; then
        printf 'Error: KB_ROOT is not set\n' >&2
        return 1
    fi

    local today
    today="$(date +%Y-%m-%d)"

    # Create directory structure
    local dirs=( ".kb" "active" "reference" "learning" "tooling" "archive" )
    for dir in "${dirs[@]}"; do
        mkdir -p "$target_dir/$dir"
    done

    # Create empty manifest.json
    cat > "$target_dir/.kb/manifest.json" <<EOF
{
  "schema_version": 1,
  "generated_at": "$(date -u '+%Y-%m-%dT%H:%M:%SZ')",
  "entries": []
}
EOF

    # Copy kb.yaml from template
    if [[ -f "$KB_ROOT/templates/kb.yaml" ]]; then
        cp "$KB_ROOT/templates/kb.yaml" "$target_dir/.kb/kb.yaml"
    else
        printf 'Warning: template kb.yaml not found at %s/templates/kb.yaml\n' "$KB_ROOT" >&2
    fi

    # Generate CLAUDE.md
    if [[ -f "$KB_ROOT/templates/CLAUDE.md" ]]; then
        sed "s/__DATE__/$today/g" "$KB_ROOT/templates/CLAUDE.md" > "$target_dir/CLAUDE.md"
    else
        # Inline fallback if template is missing
        # shellcheck disable=SC2006
        cat > "$target_dir/CLAUDE.md" <<CLAUDE_EOF
# Knowledge Base Agent Rules

> Auto-generated by kb init on $today

- The manifest is a top-level object with `schema_version`, `generated_at`, and `entries`

## Vault Structure

- active/   - entries you are actively working on
- reference/ - stable reference material
- learning/ - personal learning notes
- tooling/  - agent and tool configurations
- archive/  - completed or obsolete entries

## Rules

- Always check `.kb/manifest.json` before reading any files in this vault
- Do not scan directories or read INDEX.md for navigation; the manifest is the source of truth
- Never delete entries - move them to archive/ instead
- Keep frontmatter accurate (especially status and updated date)
- Run kb index after manual edits to keep the index current

## Manifest Query Examples

```bash
# Find active entries
jq '.entries[] | select(.tier == "active")' .kb/manifest.json

# Find entries by domain
jq '.entries[] | select(.domain == "backend")' .kb/manifest.json

# Find entries by tag
jq '.entries[] | select(.tags | index("api"))' .kb/manifest.json

# List entry IDs and titles
jq -r '.entries[] | "\(.id)\t\(.title)"' .kb/manifest.json
```
CLAUDE_EOF
    fi

    # Generate INDEX.md
    if [[ -f "$KB_ROOT/templates/INDEX.md" ]]; then
        sed "s/__DATE__/$today/g" "$KB_ROOT/templates/INDEX.md" > "$target_dir/INDEX.md"
    else
        # Inline fallback if template is missing
        # shellcheck disable=SC2006
        cat > "$target_dir/INDEX.md" <<INDEX_EOF
# Knowledge Base Index

> Auto-generated on $today. Do not edit manually - run \`kb index\` to regenerate.

## Active

| ID | Title | Domain | Updated | Tags |
|----|-------|--------|---------|------|

## Reference

| ID | Title | Domain | Updated | Tags |
|----|-------|--------|---------|------|

## Learning

| ID | Title | Domain | Updated | Tags |
|----|-------|--------|---------|------|

## Tooling

| ID | Title | Domain | Updated | Tags |
|----|-------|--------|---------|------|

## Archive

_0 archived entries. Use \`kb search\` to find archived content._
INDEX_EOF
    fi

    # Create a basic .gitignore for the vault
    cat > "$target_dir/.gitignore" <<'GITIGNORE_EOF'
# kb vault gitignore
# Uncomment the next line to keep config out of version control
# .kb/kb.yaml
GITIGNORE_EOF

    # Install git hooks if requested and .git exists
    if [[ "$install_hooks" -eq 1 ]]; then
        local git_hooks_dir="$target_dir/.git/hooks"
        if [[ -d "$target_dir/.git" ]]; then
            mkdir -p "$git_hooks_dir"
            local hook_src="$KB_ROOT/hooks/pre-commit"
            if [[ -f "$hook_src" ]]; then
                cp "$hook_src" "$git_hooks_dir/pre-commit"
                chmod +x "$git_hooks_dir/pre-commit"
                printf 'Installed pre-commit hook (auto-regenerates INDEX.md and manifest.json)\n'
            else
                printf 'Warning: pre-commit hook not found at %s\n' "$hook_src" >&2
            fi
        else
            printf 'Warning: --hooks requested but no .git directory found at %s\n' "$target_dir" >&2
            printf '  Initialize git first: cd %s && git init\n' "$target_dir" >&2
        fi
    fi

    printf 'Vault initialized at %s\n' "$target_dir"
    printf '\nNext steps:\n'
    printf '  cd %s\n' "$target_dir"
    printf '  kb add "My First Entry"\n'
    printf '  kb index\n'
    if [[ "$install_hooks" -eq 0 ]]; then
        printf '  kb init --hooks    # optional: auto-index on git commit\n'
    fi
}

if [[ "${BASH_SOURCE[0]:-}" == "${0:-}" ]]; then
    kb_init "$@"
fi
